-- AlterTable
ALTER TABLE `user` ADD COLUMN `create_time` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    ADD COLUMN `description` TEXT NULL,
    ADD COLUMN `update_time` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0);
